version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_IP: zookeeper
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
